/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetStatusBase from './AssetStatusBase';
import NestedIDHref from './NestedIDHref';

/**
* The AssetStatusResponse model module.
* @module model/AssetStatusResponse
* @version 01.00.00
*/
export default class AssetStatusResponse {
    /**
    * Constructs a new <code>AssetStatusResponse</code>.
    * @alias module:model/AssetStatusResponse
    * @class
    * @extends module:model/AssetStatusBase
    * @param code {} The value must be unique. Whitespaces are trimmed.
    * @param name {} Supports translations. Whitespaces are trimmed.
    */

    constructor(code, name) {
        AssetStatusBase.call(this, code, name);
        
        
    }

    /**
    * Constructs a <code>AssetStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AssetStatusResponse} obj Optional instance to populate.
    * @return {module:model/AssetStatusResponse} The populated <code>AssetStatusResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetStatusResponse();
            
            AssetStatusBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = NestedIDHref.constructFromObject(data['tenant']);
            }
        }
        return obj;
    }

    /**
    * Id of object
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/NestedIDHref} tenant
    */
    tenant = undefined;




}
