/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NestedIDHrefTag from './NestedIDHrefTag';

/**
* The AssetInstrumentationHistory model module.
* @module model/AssetInstrumentationHistory
* @version 01.00.00
*/
export default class AssetInstrumentationHistory {
    /**
    * Constructs a new <code>AssetInstrumentationHistory</code>.
    * @alias module:model/AssetInstrumentationHistory
    * @class
    * @param instrumentation {module:model/NestedIDHrefTag} 
    * @param event {String} Event type, can be create or destroy
    * @param eventDatetime {Date} Date of the Event
    */

    constructor(instrumentation, event, eventDatetime) {
        
        
        this['instrumentation'] = instrumentation;
        this['event'] = event;
        this['event_datetime'] = eventDatetime;
        
    }

    /**
    * Constructs a <code>AssetInstrumentationHistory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AssetInstrumentationHistory} obj Optional instance to populate.
    * @return {module:model/AssetInstrumentationHistory} The populated <code>AssetInstrumentationHistory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetInstrumentationHistory();
                        
            
            if (data.hasOwnProperty('instrumentation')) {
                obj['instrumentation'] = NestedIDHrefTag.constructFromObject(data['instrumentation']);
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('event_datetime')) {
                obj['event_datetime'] = ApiClient.convertToType(data['event_datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/NestedIDHrefTag} instrumentation
    */
    instrumentation = undefined;
    /**
    * Event type, can be create or destroy
    * @member {String} event
    */
    event = undefined;
    /**
    * Date of the Event
    * @member {Date} event_datetime
    */
    event_datetime = undefined;




}
