/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NestedID from './NestedID';

/**
* The AssetIDs model module.
* @module model/AssetIDs
* @version 01.00.00
*/
export default class AssetIDs {
    /**
    * Constructs a new <code>AssetIDs</code>.
    * @alias module:model/AssetIDs
    * @class
    * @param assets {Array.<module:model/NestedID>} 
    */

    constructor(assets) {
        
        
        this['assets'] = assets;
        
    }

    /**
    * Constructs a <code>AssetIDs</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AssetIDs} obj Optional instance to populate.
    * @return {module:model/AssetIDs} The populated <code>AssetIDs</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetIDs();
                        
            
            if (data.hasOwnProperty('assets')) {
                obj['assets'] = ApiClient.convertToType(data['assets'], [NestedID]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/NestedID>} assets
    */
    assets = undefined;




}
