/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssetValueRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssetValueRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.AssetValuesRequest = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.AssetValueRequest);
  }
}(this, function(ApiClient, AssetValueRequest) {
  'use strict';




  /**
   * The AssetValuesRequest model module.
   * @module model/AssetValuesRequest
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>AssetValuesRequest</code>.
   * @alias module:model/AssetValuesRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AssetValuesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssetValuesRequest} obj Optional instance to populate.
   * @return {module:model/AssetValuesRequest} The populated <code>AssetValuesRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], [AssetValueRequest]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AssetValueRequest>} values
   */
  exports.prototype['values'] = undefined;



  return exports;
}));


