/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NestedID from './NestedID';

/**
* The CompanyBase model module.
* @module model/CompanyBase
* @version 01.00.00
*/
export default class CompanyBase {
    /**
    * Constructs a new <code>CompanyBase</code>.
    * @alias module:model/CompanyBase
    * @class
    * @param name {String} Company name. Is unique in the API. Whitespaces are trimmed
    */

    constructor(name) {
        
        
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>CompanyBase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CompanyBase} obj Optional instance to populate.
    * @return {module:model/CompanyBase} The populated <code>CompanyBase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyBase();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = NestedID.constructFromObject(data['parent']);
            }
        }
        return obj;
    }

    /**
    * Company name. Is unique in the API. Whitespaces are trimmed
    * @member {String} name
    */
    name = undefined;
    /**
    * description text of the Company
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:model/NestedID} parent
    */
    parent = undefined;




}
