/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentBase from './DocumentBase';
import NestedIDHref from './NestedIDHref';

/**
* The DocumentResponse model module.
* @module model/DocumentResponse
* @version 01.00.00
*/
export default class DocumentResponse {
    /**
    * Constructs a new <code>DocumentResponse</code>.
    * @alias module:model/DocumentResponse
    * @class
    * @extends module:model/DocumentBase
    * @param name {} Supports translations.
    */

    constructor(name) {
        DocumentBase.call(this, name);
        
        
    }

    /**
    * Constructs a <code>DocumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DocumentResponse} obj Optional instance to populate.
    * @return {module:model/DocumentResponse} The populated <code>DocumentResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentResponse();
            
            DocumentBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('classification')) {
                obj['classification'] = NestedIDHref.constructFromObject(data['classification']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = NestedIDHref.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = NestedIDHref.constructFromObject(data['tenant']);
            }
            if (data.hasOwnProperty('download_href')) {
                obj['download_href'] = ApiClient.convertToType(data['download_href'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
        }
        return obj;
    }

    /**
    * Id of object
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/NestedIDHref} classification
    */
    classification = undefined;
    /**
    * @member {module:model/NestedIDHref} status
    */
    status = undefined;
    /**
    * @member {module:model/NestedIDHref} tenant
    */
    tenant = undefined;
    /**
    * the download link
    * @member {String} download_href
    */
    download_href = undefined;
    /**
    * @member {Object} links
    */
    links = undefined;




}
