/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventBase from './EventBase';
import NestedIDHref from './NestedIDHref';

/**
* The EventResponse model module.
* @module model/EventResponse
* @version 01.00.00
*/
export default class EventResponse {
    /**
    * Constructs a new <code>EventResponse</code>.
    * @alias module:model/EventResponse
    * @class
    * @extends module:model/EventBase
    * @param name {} Name of the event
    */

    constructor(name) {
        EventBase.call(this, name);
        
        
    }

    /**
    * Constructs a <code>EventResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EventResponse} obj Optional instance to populate.
    * @return {module:model/EventResponse} The populated <code>EventResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventResponse();
            
            EventBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = NestedIDHref.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = NestedIDHref.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = NestedIDHref.constructFromObject(data['tenant']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
        }
        return obj;
    }

    /**
    * Id of object
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/NestedIDHref} status
    */
    status = undefined;
    /**
    * @member {module:model/NestedIDHref} type
    */
    type = undefined;
    /**
    * @member {module:model/NestedIDHref} tenant
    */
    tenant = undefined;
    /**
    * @member {Object} links
    */
    links = undefined;




}
