/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.EventBase = factory(root.NetilionApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EventBase model module.
   * @module model/EventBase
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>EventBase</code>.
   * Events during life cycle of assets
   * @alias module:model/EventBase
   * @class
   * @param name {String} Name of the event
   */
  var exports = function(name) {
    var _this = this;

    _this['name'] = name;




  };

  /**
   * Constructs a <code>EventBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventBase} obj Optional instance to populate.
   * @return {module:model/EventBase} The populated <code>EventBase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('responsible')) {
        obj['responsible'] = ApiClient.convertToType(data['responsible'], 'String');
      }
      if (data.hasOwnProperty('start_datetime')) {
        obj['start_datetime'] = ApiClient.convertToType(data['start_datetime'], 'String');
      }
      if (data.hasOwnProperty('end_datetime')) {
        obj['end_datetime'] = ApiClient.convertToType(data['end_datetime'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the event
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * description text of the event
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * responsible of the event
   * @member {String} responsible
   */
  exports.prototype['responsible'] = undefined;
  /**
   * start date/time of the event: format example: 2016-01-01T18:30:00
   * @member {String} start_datetime
   */
  exports.prototype['start_datetime'] = undefined;
  /**
   * end date/time of the event: format example: 2016-01-01T18:30:00
   * @member {String} end_datetime
   */
  exports.prototype['end_datetime'] = undefined;



  return exports;
}));


