/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ExtendedOrderCode model module.
* @module model/ExtendedOrderCode
* @version 01.00.00
*/
export default class ExtendedOrderCode {
    /**
    * Constructs a new <code>ExtendedOrderCode</code>.
    * @alias module:model/ExtendedOrderCode
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ExtendedOrderCode</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExtendedOrderCode} obj Optional instance to populate.
    * @return {module:model/ExtendedOrderCode} The populated <code>ExtendedOrderCode</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtendedOrderCode();
                        
            
            if (data.hasOwnProperty('extended_order_code')) {
                obj['extended_order_code'] = ApiClient.convertToType(data['extended_order_code'], 'String');
            }
        }
        return obj;
    }

    /**
    * Extended order code
    * @member {String} extended_order_code
    */
    extended_order_code = undefined;




}
