/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Link'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Link'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.Links16 = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.Link);
  }
}(this, function(ApiClient, Link) {
  'use strict';




  /**
   * The Links16 model module.
   * @module model/Links16
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>Links16</code>.
   * @alias module:model/Links16
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Links16</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Links16} obj Optional instance to populate.
   * @return {module:model/Links16} The populated <code>Links16</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('products')) {
        obj['products'] = Link.constructFromObject(data['products']);
      }
      if (data.hasOwnProperty('purchase_orders')) {
        obj['purchase_orders'] = Link.constructFromObject(data['purchase_orders']);
      }
      if (data.hasOwnProperty('documents')) {
        obj['documents'] = Link.constructFromObject(data['documents']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Link} products
   */
  exports.prototype['products'] = undefined;
  /**
   * @member {module:model/Link} purchase_orders
   */
  exports.prototype['purchase_orders'] = undefined;
  /**
   * @member {module:model/Link} documents
   */
  exports.prototype['documents'] = undefined;



  return exports;
}));


