/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Link'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Link'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.Links1 = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.Link);
  }
}(this, function(ApiClient, Link) {
  'use strict';




  /**
   * The Links1 model module.
   * @module model/Links1
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>Links1</code>.
   * @alias module:model/Links1
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>Links1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Links1} obj Optional instance to populate.
   * @return {module:model/Links1} The populated <code>Links1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('documents')) {
        obj['documents'] = Link.constructFromObject(data['documents']);
      }
      if (data.hasOwnProperty('events')) {
        obj['events'] = Link.constructFromObject(data['events']);
      }
      if (data.hasOwnProperty('nodes')) {
        obj['nodes'] = Link.constructFromObject(data['nodes']);
      }
      if (data.hasOwnProperty('instrumentations')) {
        obj['instrumentations'] = Link.constructFromObject(data['instrumentations']);
      }
      if (data.hasOwnProperty('pictures')) {
        obj['pictures'] = Link.constructFromObject(data['pictures']);
      }
      if (data.hasOwnProperty('specifications')) {
        obj['specifications'] = Link.constructFromObject(data['specifications']);
      }
      if (data.hasOwnProperty('subscriptions')) {
        obj['subscriptions'] = Link.constructFromObject(data['subscriptions']);
      }
      if (data.hasOwnProperty('health_conditions')) {
        obj['health_conditions'] = Link.constructFromObject(data['health_conditions']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Link} documents
   */
  exports.prototype['documents'] = undefined;
  /**
   * @member {module:model/Link} events
   */
  exports.prototype['events'] = undefined;
  /**
   * @member {module:model/Link} nodes
   */
  exports.prototype['nodes'] = undefined;
  /**
   * @member {module:model/Link} instrumentations
   */
  exports.prototype['instrumentations'] = undefined;
  /**
   * @member {module:model/Link} pictures
   */
  exports.prototype['pictures'] = undefined;
  /**
   * @member {module:model/Link} specifications
   */
  exports.prototype['specifications'] = undefined;
  /**
   * @member {module:model/Link} subscriptions
   */
  exports.prototype['subscriptions'] = undefined;
  /**
   * @member {module:model/Link} health_conditions
   */
  exports.prototype['health_conditions'] = undefined;



  return exports;
}));


