/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NodeResponse from './NodeResponse';
import Pagination from './Pagination';

/**
* The NodesResponse model module.
* @module model/NodesResponse
* @version 01.00.00
*/
export default class NodesResponse {
    /**
    * Constructs a new <code>NodesResponse</code>.
    * @alias module:model/NodesResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NodesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NodesResponse} obj Optional instance to populate.
    * @return {module:model/NodesResponse} The populated <code>NodesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodesResponse();
                        
            
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], [NodeResponse]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/NodeResponse>} nodes
    */
    nodes = undefined;
    /**
    * @member {module:model/Pagination} pagination
    */
    pagination = undefined;




}
