/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ProductFeatureBase model module.
* @module model/ProductFeatureBase
* @version 01.00.00
*/
export default class ProductFeatureBase {
    /**
    * Constructs a new <code>ProductFeatureBase</code>.
    * @alias module:model/ProductFeatureBase
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ProductFeatureBase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProductFeatureBase} obj Optional instance to populate.
    * @return {module:model/ProductFeatureBase} The populated <code>ProductFeatureBase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductFeatureBase();
                        
            
            if (data.hasOwnProperty('feature_key')) {
                obj['feature_key'] = ApiClient.convertToType(data['feature_key'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * natural identifier of the product feature (also used to order result)
    * @member {String} feature_key
    */
    feature_key = undefined;
    /**
    * description text of the product feature
    * @member {String} description
    */
    description = undefined;




}
