/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.ResetPasswordRequest = factory(root.NetilionApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResetPasswordRequest model module.
   * @module model/ResetPasswordRequest
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>ResetPasswordRequest</code>.
   * @alias module:model/ResetPasswordRequest
   * @class
   * @param resetPasswordToken {String} reset password token
   * @param password {String} new password
   */
  var exports = function(resetPasswordToken, password) {
    var _this = this;

    _this['reset_password_token'] = resetPasswordToken;
    _this['password'] = password;
  };

  /**
   * Constructs a <code>ResetPasswordRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResetPasswordRequest} obj Optional instance to populate.
   * @return {module:model/ResetPasswordRequest} The populated <code>ResetPasswordRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('reset_password_token')) {
        obj['reset_password_token'] = ApiClient.convertToType(data['reset_password_token'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * reset password token
   * @member {String} reset_password_token
   */
  exports.prototype['reset_password_token'] = undefined;
  /**
   * new password
   * @member {String} password
   */
  exports.prototype['password'] = undefined;



  return exports;
}));


