/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NestedIDHref from './NestedIDHref';

/**
* The SoftwareResponse model module.
* @module model/SoftwareResponse
* @version 01.00.00
*/
export default class SoftwareResponse {
    /**
    * Constructs a new <code>SoftwareResponse</code>.
    * @alias module:model/SoftwareResponse
    * @class
    * @param id {Number} Id of object
    * @param versionNumber {String} 
    * @param tenant {module:model/NestedIDHref} 
    * @param softwareType {Object} 
    * @param links {Object} 
    */

    constructor(id, versionNumber, tenant, softwareType, links) {
        
        
        this['id'] = id;
        this['version_number'] = versionNumber;
        this['tenant'] = tenant;
        this['software_type'] = softwareType;
        this['links'] = links;
        
    }

    /**
    * Constructs a <code>SoftwareResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SoftwareResponse} obj Optional instance to populate.
    * @return {module:model/SoftwareResponse} The populated <code>SoftwareResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SoftwareResponse();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('version_number')) {
                obj['version_number'] = ApiClient.convertToType(data['version_number'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = NestedIDHref.constructFromObject(data['tenant']);
            }
            if (data.hasOwnProperty('software_type')) {
                obj['software_type'] = ApiClient.convertToType(data['software_type'], Object);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
        }
        return obj;
    }

    /**
    * Id of object
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} version_number
    */
    version_number = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:model/NestedIDHref} tenant
    */
    tenant = undefined;
    /**
    * @member {Object} software_type
    */
    software_type = undefined;
    /**
    * @member {Object} links
    */
    links = undefined;




}
