/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillingAddressResponse from './BillingAddressResponse';
import NestedIDHref from './NestedIDHref';
import NestedIDHrefName from './NestedIDHrefName';
import ShippingAddressResponse from './ShippingAddressResponse';
import SubscriptionBase from './SubscriptionBase';

/**
* The SubscriptionResponse model module.
* @module model/SubscriptionResponse
* @version 01.00.00
*/
export default class SubscriptionResponse {
    /**
    * Constructs a new <code>SubscriptionResponse</code>.
    * @alias module:model/SubscriptionResponse
    * @class
    * @extends module:model/SubscriptionBase
    */

    constructor() {
        SubscriptionBase.call(this);
        
        
    }

    /**
    * Constructs a <code>SubscriptionResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SubscriptionResponse} obj Optional instance to populate.
    * @return {module:model/SubscriptionResponse} The populated <code>SubscriptionResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionResponse();
            
            SubscriptionBase.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = NestedIDHref.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('client_application')) {
                obj['client_application'] = NestedIDHrefName.constructFromObject(data['client_application']);
            }
            if (data.hasOwnProperty('billing_address')) {
                obj['billing_address'] = BillingAddressResponse.constructFromObject(data['billing_address']);
            }
            if (data.hasOwnProperty('shipping_address')) {
                obj['shipping_address'] = ShippingAddressResponse.constructFromObject(data['shipping_address']);
            }
            if (data.hasOwnProperty('successor')) {
                obj['successor'] = NestedIDHref.constructFromObject(data['successor']);
            }
            if (data.hasOwnProperty('predecessor')) {
                obj['predecessor'] = NestedIDHref.constructFromObject(data['predecessor']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
        }
        return obj;
    }

    /**
    * Id of object
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/NestedIDHref} user
    */
    user = undefined;
    /**
    * @member {module:model/NestedIDHrefName} client_application
    */
    client_application = undefined;
    /**
    * @member {module:model/BillingAddressResponse} billing_address
    */
    billing_address = undefined;
    /**
    * @member {module:model/ShippingAddressResponse} shipping_address
    */
    shipping_address = undefined;
    /**
    * @member {module:model/NestedIDHref} successor
    */
    successor = undefined;
    /**
    * @member {module:model/NestedIDHref} predecessor
    */
    predecessor = undefined;
    /**
    * @member {Object} links
    */
    links = undefined;




}
