/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SubscriptionSeatBase model module.
* @module model/SubscriptionSeatBase
* @version 01.00.00
*/
export default class SubscriptionSeatBase {
    /**
    * Constructs a new <code>SubscriptionSeatBase</code>.
    * @alias module:model/SubscriptionSeatBase
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SubscriptionSeatBase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SubscriptionSeatBase} obj Optional instance to populate.
    * @return {module:model/SubscriptionSeatBase} The populated <code>SubscriptionSeatBase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionSeatBase();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
    * status of the subscription seat, can be invited, pending, accepted
    * @member {String} status
    */
    status = undefined;
    /**
    * email of users to be invited as new netilion user
    * @member {String} email
    */
    email = undefined;




}
