/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BillingAddressRequest', 'model/NestedID', 'model/ShippingAddressRequest', 'model/SubscriptionBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BillingAddressRequest'), require('./NestedID'), require('./ShippingAddressRequest'), require('./SubscriptionBase'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.SubscriptionRequest = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.BillingAddressRequest, root.NetilionApiDocumentation.NestedID, root.NetilionApiDocumentation.ShippingAddressRequest, root.NetilionApiDocumentation.SubscriptionBase);
  }
}(this, function(ApiClient, BillingAddressRequest, NestedID, ShippingAddressRequest, SubscriptionBase) {
  'use strict';




  /**
   * The SubscriptionRequest model module.
   * @module model/SubscriptionRequest
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>SubscriptionRequest</code>.
   * @alias module:model/SubscriptionRequest
   * @class
   * @extends module:model/SubscriptionBase
   */
  var exports = function() {
    var _this = this;
    SubscriptionBase.call(_this);






  };

  /**
   * Constructs a <code>SubscriptionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionRequest} obj Optional instance to populate.
   * @return {module:model/SubscriptionRequest} The populated <code>SubscriptionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      SubscriptionBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('user')) {
        obj['user'] = NestedID.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('client_application')) {
        obj['client_application'] = NestedID.constructFromObject(data['client_application']);
      }
      if (data.hasOwnProperty('billing_address')) {
        obj['billing_address'] = BillingAddressRequest.constructFromObject(data['billing_address']);
      }
      if (data.hasOwnProperty('shipping_address')) {
        obj['shipping_address'] = ShippingAddressRequest.constructFromObject(data['shipping_address']);
      }
      if (data.hasOwnProperty('successor')) {
        obj['successor'] = NestedID.constructFromObject(data['successor']);
      }
      if (data.hasOwnProperty('predecessor')) {
        obj['predecessor'] = NestedID.constructFromObject(data['predecessor']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(SubscriptionBase.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/NestedID} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {module:model/NestedID} client_application
   */
  exports.prototype['client_application'] = undefined;
  /**
   * @member {module:model/BillingAddressRequest} billing_address
   */
  exports.prototype['billing_address'] = undefined;
  /**
   * @member {module:model/ShippingAddressRequest} shipping_address
   */
  exports.prototype['shipping_address'] = undefined;
  /**
   * @member {module:model/NestedID} successor
   */
  exports.prototype['successor'] = undefined;
  /**
   * @member {module:model/NestedID} predecessor
   */
  exports.prototype['predecessor'] = undefined;



  return exports;
}));


