/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TechnicalUserBase model module.
* @module model/TechnicalUserBase
* @version 01.00.00
*/
export default class TechnicalUserBase {
    /**
    * Constructs a new <code>TechnicalUserBase</code>.
    * @alias module:model/TechnicalUserBase
    * @class
    * @param email {String} needs to be a valid email address
    */

    constructor(email) {
        
        
        this['email'] = email;
        
    }

    /**
    * Constructs a <code>TechnicalUserBase</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TechnicalUserBase} obj Optional instance to populate.
    * @return {module:model/TechnicalUserBase} The populated <code>TechnicalUserBase</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TechnicalUserBase();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * needs to be a valid email address
    * @member {String} email
    */
    email = undefined;
    /**
    * Disables user from access. Can be set by the user, but cannot be undone without an administrator.
    * @member {Boolean} disabled
    * @default false
    */
    disabled = false;




}
