/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TechnicalUserBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TechnicalUserBase'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.TechnicalUserRequest = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.TechnicalUserBase);
  }
}(this, function(ApiClient, TechnicalUserBase) {
  'use strict';




  /**
   * The TechnicalUserRequest model module.
   * @module model/TechnicalUserRequest
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>TechnicalUserRequest</code>.
   * @alias module:model/TechnicalUserRequest
   * @class
   * @extends module:model/TechnicalUserBase
   * @param email {String} needs to be a valid email address
   */
  var exports = function(email) {
    var _this = this;
    TechnicalUserBase.call(_this, email);
  };

  /**
   * Constructs a <code>TechnicalUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TechnicalUserRequest} obj Optional instance to populate.
   * @return {module:model/TechnicalUserRequest} The populated <code>TechnicalUserRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      TechnicalUserBase.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(TechnicalUserBase.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


