/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.UsageResponse = factory(root.NetilionApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UsageResponse model module.
   * @module model/UsageResponse
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>UsageResponse</code>.
   * @alias module:model/UsageResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UsageResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsageResponse} obj Optional instance to populate.
   * @return {module:model/UsageResponse} The populated <code>UsageResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('asset_count')) {
        obj['asset_count'] = ApiClient.convertToType(data['asset_count'], 'Number');
      }
      if (data.hasOwnProperty('file_storage')) {
        obj['file_storage'] = ApiClient.convertToType(data['file_storage'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Number of assets registred for this user
   * @member {Number} asset_count
   */
  exports.prototype['asset_count'] = undefined;
  /**
   * Use of storage for this user (in bytes)
   * @member {Number} file_storage
   */
  exports.prototype['file_storage'] = undefined;



  return exports;
}));


