/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UsageResponse model module.
* @module model/UsageResponse
* @version 01.00.00
*/
export default class UsageResponse {
    /**
    * Constructs a new <code>UsageResponse</code>.
    * @alias module:model/UsageResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UsageResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UsageResponse} obj Optional instance to populate.
    * @return {module:model/UsageResponse} The populated <code>UsageResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageResponse();
                        
            
            if (data.hasOwnProperty('asset_count')) {
                obj['asset_count'] = ApiClient.convertToType(data['asset_count'], 'Number');
            }
            if (data.hasOwnProperty('file_storage')) {
                obj['file_storage'] = ApiClient.convertToType(data['file_storage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Number of assets registred for this user
    * @member {Number} asset_count
    */
    asset_count = undefined;
    /**
    * Use of storage for this user (in bytes)
    * @member {Number} file_storage
    */
    file_storage = undefined;




}
