/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NestedIDEmail from './NestedIDEmail';

/**
* The UserIDorEmails model module.
* @module model/UserIDorEmails
* @version 01.00.00
*/
export default class UserIDorEmails {
    /**
    * Constructs a new <code>UserIDorEmails</code>.
    * @alias module:model/UserIDorEmails
    * @class
    * @param users {Array.<module:model/NestedIDEmail>} 
    */

    constructor(users) {
        
        
        this['users'] = users;
        
    }

    /**
    * Constructs a <code>UserIDorEmails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserIDorEmails} obj Optional instance to populate.
    * @return {module:model/UserIDorEmails} The populated <code>UserIDorEmails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserIDorEmails();
                        
            
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [NestedIDEmail]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/NestedIDEmail>} users
    */
    users = undefined;




}
