/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NestedIDEmail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NestedIDEmail'));
  } else {
    // Browser globals (root is window)
    if (!root.NetilionApiDocumentation) {
      root.NetilionApiDocumentation = {};
    }
    root.NetilionApiDocumentation.UserIDorEmails = factory(root.NetilionApiDocumentation.ApiClient, root.NetilionApiDocumentation.NestedIDEmail);
  }
}(this, function(ApiClient, NestedIDEmail) {
  'use strict';




  /**
   * The UserIDorEmails model module.
   * @module model/UserIDorEmails
   * @version 01.00.00
   */

  /**
   * Constructs a new <code>UserIDorEmails</code>.
   * @alias module:model/UserIDorEmails
   * @class
   * @param users {Array.<module:model/NestedIDEmail>} 
   */
  var exports = function(users) {
    var _this = this;

    _this['users'] = users;
  };

  /**
   * Constructs a <code>UserIDorEmails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIDorEmails} obj Optional instance to populate.
   * @return {module:model/UserIDorEmails} The populated <code>UserIDorEmails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], [NestedIDEmail]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/NestedIDEmail>} users
   */
  exports.prototype['users'] = undefined;



  return exports;
}));


