/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NetilionApiDocumentation);
  }
}(this, function(expect, NetilionApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NetilionApiDocumentation.AssetHealthConditionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetHealthConditionApi', function() {
    describe('addHealthConditionsToAsset', function() {
      it('should call addHealthConditionsToAsset successfully', function(done) {
        //uncomment below and update the code to test addHealthConditionsToAsset
        //instance.addHealthConditionsToAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calculateAssetHealthConditions', function() {
      it('should call calculateAssetHealthConditions successfully', function(done) {
        //uncomment below and update the code to test calculateAssetHealthConditions
        //instance.calculateAssetHealthConditions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calculateAssetHealthConditionsAndUpdateAsset', function() {
      it('should call calculateAssetHealthConditionsAndUpdateAsset successfully', function(done) {
        //uncomment below and update the code to test calculateAssetHealthConditionsAndUpdateAsset
        //instance.calculateAssetHealthConditionsAndUpdateAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetHealthConditions', function() {
      it('should call getAssetHealthConditions successfully', function(done) {
        //uncomment below and update the code to test getAssetHealthConditions
        //instance.getAssetHealthConditions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHealthConditionsOfAssetTimemachine', function() {
      it('should call getHealthConditionsOfAssetTimemachine successfully', function(done) {
        //uncomment below and update the code to test getHealthConditionsOfAssetTimemachine
        //instance.getHealthConditionsOfAssetTimemachine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reaplaceHealthConditionsOfAsset', function() {
      it('should call reaplaceHealthConditionsOfAsset successfully', function(done) {
        //uncomment below and update the code to test reaplaceHealthConditionsOfAsset
        //instance.reaplaceHealthConditionsOfAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeHealthConditionsOfAsset', function() {
      it('should call removeHealthConditionsOfAsset successfully', function(done) {
        //uncomment below and update the code to test removeHealthConditionsOfAsset
        //instance.removeHealthConditionsOfAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
