/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NetilionApiDocumentation);
  }
}(this, function(expect, NetilionApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NetilionApiDocumentation.ProductHealthConditionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductHealthConditionApi', function() {
    describe('addHealthConditionsToProduct', function() {
      it('should call addHealthConditionsToProduct successfully', function(done) {
        //uncomment below and update the code to test addHealthConditionsToProduct
        //instance.addHealthConditionsToProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductHealthConditions', function() {
      it('should call getProductHealthConditions successfully', function(done) {
        //uncomment below and update the code to test getProductHealthConditions
        //instance.getProductHealthConditions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reaplaceHealthConditionsOfProduct', function() {
      it('should call reaplaceHealthConditionsOfProduct successfully', function(done) {
        //uncomment below and update the code to test reaplaceHealthConditionsOfProduct
        //instance.reaplaceHealthConditionsOfProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeHealthConditionsOfProduct', function() {
      it('should call removeHealthConditionsOfProduct successfully', function(done) {
        //uncomment below and update the code to test removeHealthConditionsOfProduct
        //instance.removeHealthConditionsOfProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
