/**
 * Netilion API Documentation
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NetilionApiDocumentation);
  }
}(this, function(expect, NetilionApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NetilionApiDocumentation.SubscriptionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscriptionApi', function() {
    describe('addAssetsToSubscription', function() {
      it('should call addAssetsToSubscription successfully', function(done) {
        //uncomment below and update the code to test addAssetsToSubscription
        //instance.addAssetsToSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSubscription', function() {
      it('should call createSubscription successfully', function(done) {
        //uncomment below and update the code to test createSubscription
        //instance.createSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSubscription', function() {
      it('should call deleteSubscription successfully', function(done) {
        //uncomment below and update the code to test deleteSubscription
        //instance.deleteSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsOfSubscription', function() {
      it('should call getAssetsOfSubscription successfully', function(done) {
        //uncomment below and update the code to test getAssetsOfSubscription
        //instance.getAssetsOfSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSpecificationsOfSubscription', function() {
      it('should call getSpecificationsOfSubscription successfully', function(done) {
        //uncomment below and update the code to test getSpecificationsOfSubscription
        //instance.getSpecificationsOfSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubscriptionById', function() {
      it('should call getSubscriptionById successfully', function(done) {
        //uncomment below and update the code to test getSubscriptionById
        //instance.getSubscriptionById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSubscriptions', function() {
      it('should call getSubscriptions successfully', function(done) {
        //uncomment below and update the code to test getSubscriptions
        //instance.getSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeAssetsFromSubscription', function() {
      it('should call removeAssetsFromSubscription successfully', function(done) {
        //uncomment below and update the code to test removeAssetsFromSubscription
        //instance.removeAssetsFromSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeSpecificationsFromSubscriptions', function() {
      it('should call removeSpecificationsFromSubscriptions successfully', function(done) {
        //uncomment below and update the code to test removeSpecificationsFromSubscriptions
        //instance.removeSpecificationsFromSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('renameSpecificationsOfSubscriptions', function() {
      it('should call renameSpecificationsOfSubscriptions successfully', function(done) {
        //uncomment below and update the code to test renameSpecificationsOfSubscriptions
        //instance.renameSpecificationsOfSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceAssetsOfSubscription', function() {
      it('should call replaceAssetsOfSubscription successfully', function(done) {
        //uncomment below and update the code to test replaceAssetsOfSubscription
        //instance.replaceAssetsOfSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSpecificationsOfSubscriptions', function() {
      it('should call updateSpecificationsOfSubscriptions successfully', function(done) {
        //uncomment below and update the code to test updateSpecificationsOfSubscriptions
        //instance.updateSpecificationsOfSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSubscription', function() {
      it('should call updateSubscription successfully', function(done) {
        //uncomment below and update the code to test updateSubscription
        //instance.updateSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
